[2024-08-14T22:49:15.117+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-14T22:49:15.135+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-08-14T22:49:13.026214+00:00 [queued]>
[2024-08-14T22:49:15.141+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-08-14T22:49:13.026214+00:00 [queued]>
[2024-08-14T22:49:15.141+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-14T22:49:15.150+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): reddit_extraction> on 2024-08-14 22:49:13.026214+00:00
[2024-08-14T22:49:15.160+0000] {standard_task_runner.py:64} INFO - Started process 53 to run task
[2024-08-14T22:49:15.164+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 'reddit_extraction', 'manual__2024-08-14T22:49:13.026214+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpwdf119ys']
[2024-08-14T22:49:15.166+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask reddit_extraction
[2024-08-14T22:49:15.227+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-08-14T22:49:13.026214+00:00 [running]> on host 15d5e5353726
[2024-08-14T22:49:15.306+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Dinesh Saraswat' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='reddit_extraction' AIRFLOW_CTX_EXECUTION_DATE='2024-08-14T22:49:13.026214+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-14T22:49:13.026214+00:00'
[2024-08-14T22:49:15.307+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-14T22:49:15.327+0000] {logging_mixin.py:188} INFO - name 'praw' is not defined
[2024-08-14T22:49:15.327+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-14T22:49:15.327+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/etls/reddit_etl.py", line 5, in connect_reddit
    reddit = praw.Reddit(client_id = client_id,
NameError: name 'praw' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 7, in reddit_pipeline
    instance = connect_reddit(CLIENT_ID, SECRET, 'Airscholar Agent')
  File "/opt/airflow/etls/reddit_etl.py", line 12, in connect_reddit
    sys.exit(1)
NameError: name 'sys' is not defined
[2024-08-14T22:49:15.336+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=reddit_extraction, run_id=manual__2024-08-14T22:49:13.026214+00:00, execution_date=20240814T224913, start_date=20240814T224915, end_date=20240814T224915
[2024-08-14T22:49:15.345+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task reddit_extraction (name 'sys' is not defined; 53)
[2024-08-14T22:49:15.382+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-14T22:49:15.398+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-14T22:49:15.399+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
